name: Build .NET MAUI App Android

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    #keystore
    - name: Setup Keystore File
      run: |
        echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" > myapp.keystore
        sha256sum myapp.keystore
      

    #android sdk
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    #build
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Install .NET MAUI
      run: dotnet workload install maui-android
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build MauiTestWorkflow/MauiTestWorkflow.csproj -c Release -f net8.0-android /p:AndroidSigningKeyStore=myapp.keystore /p:AndroidSigningKeyAlias=ghactionskey /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_ALIAS }}" --no-restore /p:DefineConstants=DEVELOP
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: |
          ./**/*.aab
          ./**/*.apk

    #appcenter
    - name: App Center
      uses: wzieba/AppCenter-Github-Action@v1.3.4
      with:
        # App name followed by username e.g. wzieba/Sample-App
        appName: scriptboris-gmail.com/MAUI-test
        # Upload token - you can get one from appcenter.ms/settings
        token: 3b45ed705f9920e20fc2f8da50cbbe0e775d9d53
        # Distribution group
        group: all
        # Artefact to upload (.apk or .ipa)
        file: /home/runner/work/MauiTestWorkflow/MauiTestWorkflow/MauiTestWorkflow/bin/Release/net8.0-android/com.companyname.mauitestworkflow-Signed.apk
        #buildVersion: # optional
        # Build number parameter required for macOS .pkg and .dmg files
        #buildNumber: # optional
        # Release notes visible on release page
        #releaseNotes: # optional
        # Generate release notes based on the latest git commit
        #gitReleaseNotes: # optional
        # If true, send an email notification to the distribution group
        notifyTesters: true
        # If true, shows additional information from the action execution
        #debug: # optional
